on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
        # foi usada a referência: https://github.com/actions/setup-node
          node-version: 12